version: '3.1'
services:
  reverse-proxy:
    image: traefik:1.7-alpine
    command: >
      --docker
      --docker.watch
      --api
      --loglevel=DEBUG
    ports:
      # The HTTP port
      - 80:80
      # The Web UI (enabled by --api.insecure=true)
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - example-network
  rabbitmq:
    image: rabbitmq:3-alpine
    ports:
      - 15672:15672
      # - 5673:5672
    networks:
      - example-network
    environment:
      RABBITMQ_ERLANG_COOKIE: ${RABBITMQ_ERLANG_COOKIE}
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
      RABBITMQ_NODE_PORT: ${RABBITMQ_NODE_PORT}
    healthcheck:
      test: ['CMD', 'rabbitmqctl', 'status']
      interval: 30s
      timeout: 15s
      retries: 3
  redis:
    image: redis:5-alpine
    # ports:
    #   - 6379:6379
    networks:
      - example-network
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 30s
      timeout: 15s
      retries: 3
  app-celery-worker:
    image: jinyoungk/flask-docker-swarm-example-app:latest
    command: ['app-celery-worker']
    networks:
      - example-network
    environment:
      CELERY_BROKER_URL: ${CELERY_BROKER_URL}
      CELERY_RESULT_BACKEND: ${CELERY_RESULT_BACKEND}
      CACHE_REDIS_URL: ${CACHE_REDIS_URL}
      SESSION_TYPE: ${SESSION_TYPE}
      SESSION_REDIS_URL: ${SESSION_REDIS_URL}
    depends_on:
      - reverse-proxy
      - rabbitmq
      - redis
  app:
    image: jinyoungk/flask-docker-swarm-example-app:latest
    command: ['app']
    labels:
        - "traefik.enable=true"
        - "traefik.port=5000"
        - "traefik.docker.network=flask-docker-swarm-example_example-network"
        - "traefik.frontend.rule=PathPrefix:/;"
        - "traefik.backend.loadbalancer.stickiness=true"
    environment:
      CELERY_BROKER_URL: ${CELERY_BROKER_URL}
      CELERY_RESULT_BACKEND: ${CELERY_RESULT_BACKEND}
      CACHE_REDIS_URL: ${CACHE_REDIS_URL}
      SESSION_TYPE: ${SESSION_TYPE}
      SESSION_REDIS_URL: ${SESSION_REDIS_URL}
    networks:
      - example-network
    depends_on:
      - reverse-proxy
      - rabbitmq
      - redis
      - app-celery-worker

networks:
  example-network:
    driver: bridge
