version: '3.1'
services:
  nginx-proxy:
    image: jwilder/nginx-proxy:latest
    command: >
      bash -c "

      sed -i -e 's/^\(upstream .*\)/\1 \n     ip_hash;/g' nginx.tmpl ;
      forego start -r
      "
    ports:
      # The HTTP port
      - 80:80
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - example-network
    depends_on:
      - app
  rabbitmq:
    image: rabbitmq:3-alpine
    ports:
      - 15672:15672
      # - 5673:5672
    networks:
      - example-network
    environment:
      RABBITMQ_ERLANG_COOKIE: ${RABBITMQ_ERLANG_COOKIE}
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
      RABBITMQ_NODE_PORT: ${RABBITMQ_NODE_PORT}
    healthcheck:
      test: ['CMD', 'rabbitmqctl', 'status']
      interval: 30s
      timeout: 15s
      retries: 3
  redis:
    image: redis:5-alpine
    # ports:
    #   - 6379:6379
    networks:
      - example-network
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 30s
      timeout: 15s
      retries: 3
  app-celery-worker:
    image: jinyoungk/flask-docker-swarm-example-app:latest
    command: ['app-celery-worker']
    networks:
      - example-network
    environment:
      CELERY_BROKER_URL: ${CELERY_BROKER_URL}
      CELERY_RESULT_BACKEND: ${CELERY_RESULT_BACKEND}
      CACHE_REDIS_URL: ${CACHE_REDIS_URL}
      SESSION_TYPE: ${SESSION_TYPE}
      SESSION_REDIS_URL: ${SESSION_REDIS_URL}
    depends_on:
      - rabbitmq
      - redis
  app:
    image: jinyoungk/flask-docker-swarm-example-app:latest
    command: ['app', '0.0.0.0:80']
    expose:
      - 80
    networks:
      - example-network
    environment:
      VIRTUAL_HOST: app.local,localhost
      VIRTUAL_PORT: 80
      VIRTUAL_NETWORK: example-network
      CELERY_BROKER_URL: ${CELERY_BROKER_URL}
      CELERY_RESULT_BACKEND: ${CELERY_RESULT_BACKEND}
      CACHE_REDIS_URL: ${CACHE_REDIS_URL}
      SESSION_TYPE: ${SESSION_TYPE}
      SESSION_REDIS_URL: ${SESSION_REDIS_URL}
    depends_on:
      - rabbitmq
      - redis
      - app-celery-worker

networks:
  example-network:
    driver: bridge
